//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPS_DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLC
    {
        public string AdmissionID { get; set; }
        public decimal AadharCard { get; set; }
        public string FirstName { get; set; }
        public string FatherName { get; set; }
        public string LastName { get; set; }
        public string MotherName { get; set; }
        public string Nationality { get; set; }
        public string MotherTongue { get; set; }
        public string Religion { get; set; }
        public string Cast { get; set; }
        public string SubCast { get; set; }
        public string BirthPlace { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public System.DateTime DOB { get; set; }
        public string DOB_In_Words { get; set; }
        public string PreviousSchool { get; set; }
        public string Division { get; set; }
        public string AdmissionDate { get; set; }
        public string AdmissionDivision { get; set; }
        public string Performance { get; set; }
        public string Behaviour { get; set; }
        public System.DateTime SchoolLeaveDate { get; set; }
        public string CurrentDivision { get; set; }
        public string Reason { get; set; }
    }
}
